# Generated by Django 2.2.6 on 2019-10-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='searchtext',
            field=models.SlugField(max_length=200),
        ),
    ]
