# Generated by Django 2.2.6 on 2019-10-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20191022_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
